CREATE GENERATOR gen_traduzioni_id;
SET GENERATOR gen_traduzioni_id TO 0;
set term !! ;
CREATE TRIGGER TRADUZIONI_BI FOR TRADUZIONI
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
if (NEW.ID is NULL) then NEW.ID = GEN_ID(GEN_TRADUZIONI_ID, 1);
END!!
set term ; !!